server:
  port: 8091
spring:
 application:
  name: ContactService  
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
      defaultZone: http://localhost:8761/eureka/
  