server:
 port: 8080
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: ApiGateWayService
 cloud:
    gateway:
      routes:
      - id: ContactModule
        uri: http://localhost:8091/
        predicates:
        - Path=/api/v1/findAllContacts/**
      - id: ArticleModule
        uri: http://localhost:8087/
        predicates:
        - Path=/api/v1/findallArticles/**
      - id: LifeStyleModule
        uri: http://localhost:8088/
        predicates:
        - Path=/api/v1/findallLifeStyles/**
      - id: TechnologyModule
        uri: http://localhost:8089/
        predicates:
        - Path=/api/v1/findalltechnology/**